name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: serenis
        ports:
          - 3306:3306
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Build
        run: |
          pnpm build

      - name: Types
        run: |
          pnpm typecheck

      - name: Lint
        run: |
          pnpm lint

      - name: Test
        run: pnpm test
